# Generated by Django 3.1.1 on 2020-09-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell',
            field=models.IntegerField(default='+880'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
